analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - prefer_named_parameters:
      threshold: 2
    - incorrect_todo_comment:
      severity: error
    - prefer_is_empty_string:
    - prefer_is_not_empty_string:
    - avoid_unnecessary_async_function:
    - prefer_async_await:
    - prefer_lower_case_test_description:
      test_methods:
        - method_name: "test"
          param_name: "description"
        - method_name: "blocTest"
          param_name: "desc"
    - test_folder_must_mirror_lib_folder:
      lib_folder_path: "lib/test_folder_must_mirror_lib_folder_test/lib"
      test_folder_paths:
        - "lib/test_folder_must_mirror_lib_folder_test/test/ut"
        - "lib/test_folder_must_mirror_lib_folder_test/it"
      includes:
        - "lib/test_folder_must_mirror_lib_folder_test/**/*.dart"
    - incorrect_parent_class:
      class_post_fixes:
        - "Page"
        - "Screen"
      parent_class_pre_fixes:
        - "Base"
        - "Abstract"
    - prefer_importing_index_file:
    - missing_expanded_or_flexible:
    - avoid_using_text_style_constructor_directly:
    - util_functions_must_be_static:
      utils_folder_path: "lib/util_functions_must_be_static_test/utils"
    - missing_run_catching:
    - avoid_using_if_else_with_enums:
    - avoid_nested_conditions:
      acceptable_level: 3
    - missing_log_in_catch_block:
      class_name: "Log"
      methods:
        - "severe"
        - "warning"
        - "info"
        - "debug"
        - "error"
    - missing_extension_method_for_events:
    - missing_common_scrollbar:
      common_scrollbar_widget_name: "CommonScrollbar"
    - avoid_dynamic:
    - avoid_hard_coded_colors:
    - prefer_common_widgets:
    - avoid_hard_coded_strings:
    - incorrect_screen_name_parameter_value:
    - incorrect_screen_name_enum_value:
    - incorrect_event_parameter_name:
    - incorrect_event_parameter_type:
    - incorrect_event_name:
    - avoid_using_datetime_now:
    - avoid_using_enum_name_as_key:
    - avoid_using_unsafe_cast:
    - prefer_single_widget_per_file:
    - incorrect_freezed_default_value_type:
    - require_matching_file_and_class_name:
    - missing_golden_test:
      widget_folders:
        - "lib/missing_golden_test_test/lib"
      test_folder: "lib/missing_golden_test_test/test"
    - invalid_test_group_name:
      valid_group_names:
        - "design"
        - "others"
      includes:
        - "lib/invalid_test_group_name_test/**/*.dart"
    - avoid_using_datetime_now:
    - empty_test_group:
    - incorrect_golden_image_name:
      severity: error
      excludes:
        - "lib/excluded_test/**/*.dart"
      includes:
        - "**/*_test.dart"
    - missing_test_group:
      required_groups:
        - "design"
        - "others"
      includes:
        - "lib/missing_test_group_test/test_test.dart"